# Generated by Django 4.2.4 on 2023-11-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie',
            new_name='course',
        ),
    ]
